### PR TITLE
Waypoint TP Feature

### PR DESCRIPTION
**Pull request by w0dash**
Stolen from emoisback, but improved

image

### CODE REVIEW

**Comment by EshwarYT** [comment]
Infinite health affects the recall of pals

**Comment by AbhishekAEDan** [comment]
> > Infinite health affects the recall of pals
> 
> I think you need to open an Issue instead of commenting my PullRequest... 🫠

sorry i made an error and tried to delete it lol

**Comment by w0dash** [comment]
> > > Infinite health affects the recall of pals
> > 
> > 
> > I think you need to open an Issue instead of commenting my PullRequest... 🫠
> 
> sorry i made an error and tried to delete it lol

np, but I deleted my answer as well now 🤣

**Comment by bycEEE** [comment]
Has this been working reliably for you? I'm able to teleport to some locations perfectly fine, others put me in a loading screen and warps me back to base.

**Comment by w0dash** [comment]
> Has this been working reliably for you? I'm able to teleport to some locations perfectly fine, others put me in a loading screen and warps me back to base.

Tbh I didn't test it that much yet, all few locations I tried seemed to work, but I can test it some more tomorrow.

The "automatic" option definitely has some quirks though I think.

**Comment by bycEEE** [comment]
When you're free can you test the following locations? Trying to see if my issue is replicable.

Not working:
- 185,166
- 400, 490
- -90, 150
- -300, -300
- -700, -450

**Comment by bycEEE** [comment]
> all few locations I tried seemed to work

Luck of the draw lol. The first couple of random locations I tried didn't work.

**Comment by w0dash** [comment]
You are right, some locations don't work.

At first I thought it was because every waypoint has a height of Z = 0.0, but raising that value before teleporting does not work properly either it seems. 

I am not sure yet how to fix it...

**Comment by w0dash** [comment]
It should work better now atleast I think.

**Comment by w0dash** [comment]
Maybe someone else can try it again too.

**Comment by NuLLxD** [comment]
Closed PR. Verified and added to master with credits. Thanks for collabing.

Edit: I noticed a remake character feature was included in the PR that I wasn't sure if you wanted pushed. If you intended to have that in the PR please open another for that feature. Thank you.

**Comment by w0dash** [comment]
No, the remake character thing wasn't even working and I thought I had it removed already, so everything is fine. 👌

**Pull request closed without merging**
